# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: "Rubel"
tagline: 'A Jekyll theme'
description: 'some'
url: "https://rubel-hossain.github.io/"
baseurl: ""

author:
  name: 'Mark Otto'
  url:  'https://twitter.com/rubel8525'

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: 'https://github.com/poole/rubel-hossain'
